# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-24 04:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0002_semester_2_semester_3_semester_4_semester_5_semester_6_semester_7_semester_8'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Semester_3',
            new_name='Semester2',
        ),
        migrations.RenameModel(
            old_name='Semester_2',
            new_name='Semester3',
        ),
    ]
