# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-25 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0005_courses_sem1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses_sem1',
            new_name='Course1_sem1',
        ),
    ]
