# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-25 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0006_auto_20181025_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='course1_sem1',
            name='course_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
