# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-26 19:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0008_course2_sem1_course3_sem1_course4_sem1_course5_sem1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course1_sem2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30, null=True)),
                ('file_pdfs', models.FileField(null=True, upload_to='')),
                ('video_link', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('course_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.Semester_1')),
            ],
        ),
        migrations.CreateModel(
            name='Course1_sem3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30, null=True)),
                ('file_pdfs', models.FileField(null=True, upload_to='')),
                ('video_link', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('course_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.Semester_1')),
            ],
        ),
        migrations.CreateModel(
            name='Course1_sem4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30, null=True)),
                ('file_pdfs', models.FileField(null=True, upload_to='')),
                ('video_link', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('course_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.Semester_1')),
            ],
        ),
        migrations.CreateModel(
            name='Course1_sem5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30, null=True)),
                ('file_pdfs', models.FileField(null=True, upload_to='')),
                ('video_link', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('course_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.Semester_1')),
            ],
        ),
        migrations.CreateModel(
            name='Course1_sem6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30, null=True)),
                ('file_pdfs', models.FileField(null=True, upload_to='')),
                ('video_link', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('course_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.Semester_1')),
            ],
        ),
        migrations.CreateModel(
            name='Course1_sem7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30, null=True)),
                ('file_pdfs', models.FileField(null=True, upload_to='')),
                ('video_link', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('course_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.Semester_1')),
            ],
        ),
        migrations.CreateModel(
            name='Course1_sem8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30, null=True)),
                ('file_pdfs', models.FileField(null=True, upload_to='')),
                ('video_link', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('course_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.Semester_1')),
            ],
        ),
        migrations.CreateModel(
            name='Course2_sem2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30, null=True)),
                ('file_pdfs', models.FileField(null=True, upload_to='')),
                ('video_link', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('course_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.Semester_1')),
            ],
        ),
        migrations.CreateModel(
            name='Course2_sem3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30, null=True)),
                ('file_pdfs', models.FileField(null=True, upload_to='')),
                ('video_link', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('course_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.Semester_1')),
            ],
        ),
        migrations.CreateModel(
            name='Course2_sem4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30, null=True)),
                ('file_pdfs', models.FileField(null=True, upload_to='')),
                ('video_link', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('course_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.Semester_1')),
            ],
        ),
        migrations.CreateModel(
            name='Course2_sem5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30, null=True)),
                ('file_pdfs', models.FileField(null=True, upload_to='')),
                ('video_link', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('course_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.Semester_1')),
            ],
        ),
        migrations.CreateModel(
            name='Course2_sem6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30, null=True)),
                ('file_pdfs', models.FileField(null=True, upload_to='')),
                ('video_link', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('course_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.Semester_1')),
            ],
        ),
        migrations.CreateModel(
            name='Course2_sem7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30, null=True)),
                ('file_pdfs', models.FileField(null=True, upload_to='')),
                ('video_link', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('course_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.Semester_1')),
            ],
        ),
        migrations.CreateModel(
            name='Course3_sem2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30, null=True)),
                ('file_pdfs', models.FileField(null=True, upload_to='')),
                ('video_link', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('course_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.Semester_1')),
            ],
        ),
        migrations.CreateModel(
            name='Course3_sem3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30, null=True)),
                ('file_pdfs', models.FileField(null=True, upload_to='')),
                ('video_link', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('course_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.Semester_1')),
            ],
        ),
        migrations.CreateModel(
            name='Course3_sem4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30, null=True)),
                ('file_pdfs', models.FileField(null=True, upload_to='')),
                ('video_link', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('course_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.Semester_1')),
            ],
        ),
        migrations.CreateModel(
            name='Course3_sem5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30, null=True)),
                ('file_pdfs', models.FileField(null=True, upload_to='')),
                ('video_link', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('course_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.Semester_1')),
            ],
        ),
        migrations.CreateModel(
            name='Course3_sem6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30, null=True)),
                ('file_pdfs', models.FileField(null=True, upload_to='')),
                ('video_link', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('course_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.Semester_1')),
            ],
        ),
        migrations.CreateModel(
            name='Course3_sem7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30, null=True)),
                ('file_pdfs', models.FileField(null=True, upload_to='')),
                ('video_link', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('course_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.Semester_1')),
            ],
        ),
        migrations.CreateModel(
            name='Course4_sem2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30, null=True)),
                ('file_pdfs', models.FileField(null=True, upload_to='')),
                ('video_link', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('course_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.Semester_1')),
            ],
        ),
        migrations.CreateModel(
            name='Course4_sem3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30, null=True)),
                ('file_pdfs', models.FileField(null=True, upload_to='')),
                ('video_link', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('course_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.Semester_1')),
            ],
        ),
        migrations.CreateModel(
            name='Course4_sem4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30, null=True)),
                ('file_pdfs', models.FileField(null=True, upload_to='')),
                ('video_link', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('course_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.Semester_1')),
            ],
        ),
        migrations.CreateModel(
            name='Course4_sem5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30, null=True)),
                ('file_pdfs', models.FileField(null=True, upload_to='')),
                ('video_link', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('course_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.Semester_1')),
            ],
        ),
        migrations.CreateModel(
            name='Course4_sem6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30, null=True)),
                ('file_pdfs', models.FileField(null=True, upload_to='')),
                ('video_link', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('course_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.Semester_1')),
            ],
        ),
        migrations.CreateModel(
            name='Course4_sem7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30, null=True)),
                ('file_pdfs', models.FileField(null=True, upload_to='')),
                ('video_link', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('course_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.Semester_1')),
            ],
        ),
        migrations.CreateModel(
            name='Course5_sem2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30, null=True)),
                ('file_pdfs', models.FileField(null=True, upload_to='')),
                ('video_link', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('course_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.Semester_1')),
            ],
        ),
        migrations.CreateModel(
            name='Course5_sem3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30, null=True)),
                ('file_pdfs', models.FileField(null=True, upload_to='')),
                ('video_link', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('course_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.Semester_1')),
            ],
        ),
        migrations.CreateModel(
            name='Course5_sem4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30, null=True)),
                ('file_pdfs', models.FileField(null=True, upload_to='')),
                ('video_link', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('course_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.Semester_1')),
            ],
        ),
        migrations.CreateModel(
            name='Course5_sem5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30, null=True)),
                ('file_pdfs', models.FileField(null=True, upload_to='')),
                ('video_link', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('course_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.Semester_1')),
            ],
        ),
        migrations.CreateModel(
            name='Course5_sem6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30, null=True)),
                ('file_pdfs', models.FileField(null=True, upload_to='')),
                ('video_link', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('course_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.Semester_1')),
            ],
        ),
        migrations.CreateModel(
            name='Course5_sem7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30, null=True)),
                ('file_pdfs', models.FileField(null=True, upload_to='')),
                ('video_link', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('course_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.Semester_1')),
            ],
        ),
    ]
